spring:
  jpa:
    generate-ddl: true
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/practice
    username: postgres
    password: root

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/